### ISSUE TITLE
Paper link

### ISSUE THREAD

**Issue by Vincentqyw** [SuhZhang/ConvMatch#1]
Hi Zhang,

Glad to see your new work! Could you please publish a link to this paper?  The link posted in this repo is invalid.

Thanks

**Comment by SuhZhang** [comment]
Thanks for your attention. The paper now is in the stage of submitting camera ready. We will add the link as soon as AAAI'23 provides it. If you want to read the paper now, please email suhzhang001@gmail.com.

**Comment by SuhZhang** [comment]
We have added the paper link provided by AAAI'23. The comment is closed.
