### ISSUE TITLE
Visualizing ordered and unordered motion vectors

### ISSUE THREAD

**Issue by WallofWonder** [SuhZhang/ConvMatch#2]
Excellent work! I'm curious how you visualize motion vectors like this, especially ordered motion vectors. Can you share the code or the tools you use? Thanks very much!
<img width="623" alt="image" src="https://github.com/SuhZhang/ConvMatch/assets/46950043/0033f44f-a4af-4a39-9aaa-114f0b2d5276">

**Comment by SuhZhang** [comment]
Thanks for your attention. 
For a fast implementation of the visualization of the ordered motion vectors, you can refer to [LAF](https://github.com/StaRainJ/LAF). We borrowed most of the visualization code from it.

**Comment by WallofWonder** [comment]
> Thanks for your attention. For a fast implementation of the visualization of the ordered motion vectors, you can refer to [LAF](https://github.com/StaRainJ/LAF). We borrowed most of the visualization code from it.

 Thanks a lot! I successfully visualized the unordered motion vectors. 
But I noticed that [plotTypicalMotionFiled](https://github.com/StaRainJ/LAF/blob/master/plotTypicalMotionFiled.m) receives 2D input.
Is it any effective way to visualize the 128-D ordered motion vectors in ConvMatch? I have tried some dimension reduction methods like TSNE and PCA, and they don't work well.

**Comment by SuhZhang** [comment]
You may have misunderstood the illustration. To use the network to achieve the filtering of the motion field in a learnable way, we characterize the motion vectors in a high-dimensional space, where the network determines the meaning of each dimension after training on a large amount of data, and thus it isn't easy to restore them to the real motion vectors through dimensionality reduction methods such as TSNE or PCA. Here, our illustrations are only used to visualize the function of each module and the significance of the inputs and outputs and are not the result of some kind of processing of the high-dimensional vectors.

**Comment by SuhZhang** [comment]
> > Thanks for your attention. For a fast implementation of the visualization of the ordered motion vectors, you can refer to [LAF](https://github.com/StaRainJ/LAF). We borrowed most of the visualization code from it.
> 
> Thanks a lot! I successfully visualized the unordered motion vectors. But I noticed that [plotTypicalMotionFiled](https://github.com/StaRainJ/LAF/blob/master/plotTypicalMotionFiled.m) receives 2D input. Is it any effective way to visualize the 128-D ordered motion vectors in ConvMatch? I have tried some dimension reduction methods like TSNE and PCA, and they don't work well.

You may have misunderstood the illustration. To use the network to achieve the filtering of the motion field in a learnable way, we characterize the motion vectors in a high-dimensional space, where the network determines the meaning of each dimension after training on a large amount of data, and thus it isn't easy to restore them to the real motion vectors through dimensionality reduction methods such as TSNE or PCA. Here, our illustrations are only used to visualize the function of each module and the significance of the inputs and outputs and are not the result of some kind of processing of the high-dimensional vectors.

**Comment by WallofWonder** [comment]
> > > Thanks for your attention. For a fast implementation of the visualization of the ordered motion vectors, you can refer to [LAF](https://github.com/StaRainJ/LAF). We borrowed most of the visualization code from it.
> > 
> > 
> > Thanks a lot! I successfully visualized the unordered motion vectors. But I noticed that [plotTypicalMotionFiled](https://github.com/StaRainJ/LAF/blob/master/plotTypicalMotionFiled.m) receives 2D input. Is it any effective way to visualize the 128-D ordered motion vectors in ConvMatch? I have tried some dimension reduction methods like TSNE and PCA, and they don't work well.
> 
> You may have misunderstood the illustration. To use the network to achieve the filtering of the motion field in a learnable way, we characterize the motion vectors in a high-dimensional space, where the network determines the meaning of each dimension after training on a large amount of data, and thus it isn't easy to restore them to the real motion vectors through dimensionality reduction methods such as TSNE or PCA. Here, our illustrations are only used to visualize the function of each module and the significance of the inputs and outputs and are not the result of some kind of processing of the high-dimensional vectors.

OK. Thank you for your patient explanation!
